Rename canonical to default
vmware-tanzu/kpack-cli pull request #203
Opened 2021-09-14 19:52 UTC by tylerphelan

- also refactored main package functions to its own package
  - this allows us to reuse those functions in the docs main package which can be used to generate the docs
  - I think this is typically a good pattern either way

2021-09-14 20:26 UTC, jromero requested changes
Looks like you might have accidently uploaded the `kp` binary to the repo.

2021-09-14 20:46 UTC, tylerphelan commented
@jromero whoops. I did a force push.

2021-09-14 20:50 UTC, matthewmcnew approved these changes

2021-09-15 14:13 UTC, tomkennedy513 approved these changes

2021-09-16 18:25 UTC, merged